name: docker_latex
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        env:
          DOCKER_IMAGE_ORIGIN: "ultral/docker_latex"
        run: |
          docker build . -t ${DOCKER_IMAGE_ORIGIN}:${{ github.sha }}
          docker tag ${DOCKER_IMAGE_ORIGIN}:${{ github.sha }} ${DOCKER_IMAGE_ORIGIN}:latest
          docker push ${DOCKER_IMAGE_ORIGIN}:${{ github.sha }}
          docker push ${DOCKER_IMAGE_ORIGIN}:latest
