jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Tag the image with the git commit hash
      - run: |
          docker build . -t ultral/docker_latex:${{ github.sha }}
          docker push ultral/docker_latex:${{ github.sha }}
          docker push ultral/docker_latex:latest
